language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jeancarlosjc-github"
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
