language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jeancarlosjc-github"
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      
script:
- sonar-scanner
