language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jeancarlosjc-github"
    token:
      secure: "6e83a14c1d0ccd3c00db85984e24934c03655bbd"
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
